name: kadoin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_svg: 1.0.3
  intl: 0.17.0
  auto_size_text: 3.0.0
  proste_bezier_curve: 2.0.2
  carousel_slider: 4.0.0
  introduction_screen: 3.0.0
  firebase_core: 1.13.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/images/
  uses-material-design: true

