// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNl_EMeleZhvoAhFUMaeyhSqBKXmr8p2A',
    appId: '1:645463541774:android:e1a602e619a0edc34d545f',
    messagingSenderId: '645463541774',
    projectId: 'kadoin-710ab',
    storageBucket: 'kadoin-710ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkFMbmFWsBelI5WaFEPynBuIYfzaER_HM',
    appId: '1:645463541774:ios:89b43aa410b1f3e94d545f',
    messagingSenderId: '645463541774',
    projectId: 'kadoin-710ab',
    storageBucket: 'kadoin-710ab.appspot.com',
    iosClientId: '645463541774-m9mq0uk0dksov6fcvu0lqa691c757tsi.apps.googleusercontent.com',
    iosBundleId: 'com.kadoin.app',
  );
}
